export const CRNA_SCHOOLS = [
  'Albany Medical Center',
  'Adventist University of Health Sciences',
  'Barry University',
  'Baylor College of Medicine',
  'Boston College',
  'Bryan College of Health Sciences',
  'California State University, Fullerton',
  'Case Western Reserve University',
  'Charles R. Drew University',
  'Columbia University',
  'Drexel University',
  'Duke University',
  'East Carolina University',
  'East Tennessee State University',
  'Fairfield University',
  'Florida Gulf Coast University',
  'Florida International University',
  'Georgetown University',
  'Goldfarb School of Nursing at Barnes-Jewish College',
  'Harris College of Nursing & Health Sciences at TCU',
  'Indiana Wesleyan University',
  'Johns Hopkins University',
  'Kaiser Permanente School of Anesthesia',
  'Loma Linda University',
  'Louisiana State University Health Sciences Center',
  'Marquette University',
  'Marshall University',
  'Medical University of South Carolina',
  'Middle Tennessee School of Anesthesia',
  'Midwestern University - Glendale',
  'Mount Marty University',
  'Murray State University',
  'National University',
  'Naval Medical Center Portsmouth',
  'New York University',
  'Newman University',
  'Northeastern University',
  'Northern Kentucky University',
  'Northwestern State University of Louisiana',
  'Oakland University',
  'Old Dominion University',
  'Oregon Health & Science University',
  'Otterbein University',
  'Rush University',
  'Rutgers University',
  'Sacred Heart University',
  'Samuel Merritt University',
  'South College',
  'Southern Illinois University Edwardsville',
  'SUNY Downstate Health Sciences University',
  'SUNY Upstate Medical University',
  'Texas Christian University',
  'Texas Wesleyan University',
  'The Christ College of Nursing and Health Sciences',
  'The University of Akron',
  'The University of Iowa',
  'The University of Kansas',
  'The University of North Carolina at Greensboro',
  'The University of Scranton',
  'The University of Tennessee Health Science Center',
  'The University of Texas Health Science Center at Houston',
  'Thomas Jefferson University',
  'Uniformed Services University',
  'Union University',
  'University at Buffalo',
  'University of Alabama at Birmingham',
  'University of Arkansas for Medical Sciences',
  'University of California, Los Angeles',
  'University of Cincinnati',
  'University of Colorado',
  'University of Detroit Mercy',
  'University of Florida',
  'University of Illinois at Chicago',
  'University of Indianapolis',
  'University of Maryland',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota',
  'University of Missouri - Kansas City',
  'University of New England',
  'University of New Mexico',
  'University of North Carolina at Chapel Hill',
  'University of North Dakota',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Rhode Island',
  'University of South Alabama',
  'University of South Carolina',
  'University of South Florida',
  'University of Southern California',
  'University of Southern Indiana',
  'University of Southern Mississippi',
  'University of Tennessee at Chattanooga',
  'University of Tennessee, Knoxville',
  'University of Texas at Arlington',
  'University of Texas Health Science Center at San Antonio',
  'University of Texas Medical Branch',
  'University of the Incarnate Word',
  'University of Utah',
  'University of Vermont',
  'University of Virginia',
  'University of Washington',
  'University of Wisconsin - La Crosse',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Commonwealth University',
  'Wake Forest University',
  'Wayne State University',
  'Webster University',
  'West Coast University',
  'Western Carolina University',
  'Westminster College',
  'Widener University',
  'Winona State University',
  'Winston-Salem State University',
  'Worcester State University',
  'Wolford College',
  'Xavier University',
  'Yale University',
  'Youngstown State University',
].sort();

export const ROLES = [
  'SRNA/NAR/RRNA',
  'RN',
] as const;

export const GRADUATION_YEARS = Array.from(
  { length: 2040 - 2025 + 1 },
  (_, i) => (2025 + i).toString()
);
