/*
  # Add NBCRNA Study Features

  ## Overview
  Extends the database to support NBCRNA exam preparation with study plans,
  practice questions, and progress tracking for anesthesia students.

  ## New Tables

  ### 1. `study_plans`
  Stores personalized study plans generated by AI
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users) - Owner of the study plan
  - `title` (text) - Study plan title (e.g., "6-Month NBCRNA Prep")
  - `description` (text) - AI-generated plan description
  - `exam_date` (date) - Target exam date
  - `study_hours_per_week` (integer) - Planned weekly study hours
  - `current_knowledge_level` (text) - Beginner, Intermediate, Advanced
  - `focus_areas` (jsonb) - Array of topics to focus on
  - `weekly_schedule` (jsonb) - Detailed weekly breakdown
  - `milestones` (jsonb) - Key milestones and checkpoints
  - `generated_content` (text) - Full AI-generated plan
  - `is_active` (boolean) - Whether this is the active study plan
  - `created_at` (timestamptz) - Creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 2. `study_topics`
  Master list of NBCRNA exam topics
  - `id` (uuid, primary key)
  - `category` (text) - Main category (Anatomy, Pharmacology, etc.)
  - `subcategory` (text) - Specific topic area
  - `title` (text) - Topic title
  - `description` (text) - Topic description
  - `difficulty_level` (text) - Beginner, Intermediate, Advanced
  - `estimated_study_hours` (integer) - Recommended study time
  - `nbcrna_weight` (integer) - Percentage weight on actual exam
  - `created_at` (timestamptz) - Creation timestamp

  ### 3. `practice_questions`
  Practice questions for NBCRNA preparation
  - `id` (uuid, primary key)
  - `topic_id` (uuid, references study_topics) - Associated topic
  - `question_text` (text) - The question
  - `question_type` (text) - multiple_choice, true_false, case_study
  - `options` (jsonb) - Answer choices for multiple choice
  - `correct_answer` (text) - The correct answer
  - `explanation` (text) - Detailed explanation of the answer
  - `difficulty_level` (text) - Easy, Medium, Hard
  - `source` (text) - AI-generated or imported
  - `created_at` (timestamptz) - Creation timestamp

  ### 4. `user_question_attempts`
  Tracks user attempts at practice questions
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users) - User who attempted
  - `question_id` (uuid, references practice_questions) - Question attempted
  - `user_answer` (text) - User's selected answer
  - `is_correct` (boolean) - Whether answer was correct
  - `time_spent_seconds` (integer) - Time taken to answer
  - `confidence_level` (text) - User's confidence (low, medium, high)
  - `created_at` (timestamptz) - Attempt timestamp

  ### 5. `study_sessions`
  Tracks individual study sessions
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users) - User's session
  - `study_plan_id` (uuid, references study_plans) - Associated plan
  - `topic_id` (uuid, references study_topics) - Topic studied
  - `duration_minutes` (integer) - Session length
  - `questions_attempted` (integer) - Number of questions answered
  - `questions_correct` (integer) - Number answered correctly
  - `notes` (text) - Session notes
  - `created_at` (timestamptz) - Session timestamp

  ## Security
  - Enable RLS on all tables
  - Users can only access their own study plans, attempts, and sessions
  - Study topics and practice questions are readable by all authenticated users
  - Only authenticated users can create study content

  ## Indexes
  - Index on user_id for fast user-specific queries
  - Index on topic_id for filtering by topic
  - Index on created_at for chronological sorting
  - Index on is_active for finding active study plans
*/

-- Create study_plans table
CREATE TABLE IF NOT EXISTS study_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  description text,
  exam_date date,
  study_hours_per_week integer DEFAULT 10,
  current_knowledge_level text DEFAULT 'Intermediate',
  focus_areas jsonb DEFAULT '[]'::jsonb,
  weekly_schedule jsonb DEFAULT '{}'::jsonb,
  milestones jsonb DEFAULT '[]'::jsonb,
  generated_content text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create study_topics table
CREATE TABLE IF NOT EXISTS study_topics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL,
  subcategory text,
  title text NOT NULL,
  description text,
  difficulty_level text DEFAULT 'Intermediate',
  estimated_study_hours integer DEFAULT 5,
  nbcrna_weight integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Create practice_questions table
CREATE TABLE IF NOT EXISTS practice_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id uuid REFERENCES study_topics(id) ON DELETE SET NULL,
  question_text text NOT NULL,
  question_type text DEFAULT 'multiple_choice',
  options jsonb DEFAULT '[]'::jsonb,
  correct_answer text NOT NULL,
  explanation text,
  difficulty_level text DEFAULT 'Medium',
  source text DEFAULT 'AI-generated',
  created_at timestamptz DEFAULT now()
);

-- Create user_question_attempts table
CREATE TABLE IF NOT EXISTS user_question_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  question_id uuid REFERENCES practice_questions(id) ON DELETE CASCADE NOT NULL,
  user_answer text NOT NULL,
  is_correct boolean NOT NULL,
  time_spent_seconds integer DEFAULT 0,
  confidence_level text,
  created_at timestamptz DEFAULT now()
);

-- Create study_sessions table
CREATE TABLE IF NOT EXISTS study_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  study_plan_id uuid REFERENCES study_plans(id) ON DELETE SET NULL,
  topic_id uuid REFERENCES study_topics(id) ON DELETE SET NULL,
  duration_minutes integer DEFAULT 0,
  questions_attempted integer DEFAULT 0,
  questions_correct integer DEFAULT 0,
  notes text,
  created_at timestamptz DEFAULT now()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_study_plans_user_id ON study_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_study_plans_is_active ON study_plans(is_active);
CREATE INDEX IF NOT EXISTS idx_study_topics_category ON study_topics(category);
CREATE INDEX IF NOT EXISTS idx_practice_questions_topic ON practice_questions(topic_id);
CREATE INDEX IF NOT EXISTS idx_user_attempts_user_id ON user_question_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_user_attempts_question_id ON user_question_attempts(question_id);
CREATE INDEX IF NOT EXISTS idx_study_sessions_user_id ON study_sessions(user_id);

-- Enable Row Level Security
ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE practice_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_question_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for study_plans
CREATE POLICY "Users can view own study plans"
  ON study_plans FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own study plans"
  ON study_plans FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own study plans"
  ON study_plans FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own study plans"
  ON study_plans FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- RLS Policies for study_topics (readable by all authenticated users)
CREATE POLICY "Authenticated users can view topics"
  ON study_topics FOR SELECT
  TO authenticated
  USING (true);

-- RLS Policies for practice_questions (readable by all authenticated users)
CREATE POLICY "Authenticated users can view questions"
  ON practice_questions FOR SELECT
  TO authenticated
  USING (true);

-- RLS Policies for user_question_attempts
CREATE POLICY "Users can view own attempts"
  ON user_question_attempts FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own attempts"
  ON user_question_attempts FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- RLS Policies for study_sessions
CREATE POLICY "Users can view own sessions"
  ON study_sessions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own sessions"
  ON study_sessions FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions"
  ON study_sessions FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);